import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Masthead from '../components/masthead'
import AboutUs from '../components/aboutus'
import Skills from '../components/skills'
import Works from '../components/works'
import Footer from '../components/footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>World Roleplay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/masthead_bg.gif" />
      </Head>

      <Masthead />  
      <AboutUs />
      <Skills />
      <Works />

      <Footer />
    </div>
  )
}
