import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Masthead from '../components/masthead'
import AboutUs from '../components/aboutus'
import Skills from '../components/skills'
import Works from '../components/works'

export default function Home() {
  return (
    <div>
      <Head>
        <title>World Roleplay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/masthead_bg.gif" />
      </Head>

      <Masthead />  
      <AboutUs />
      <Skills />
      <Works />

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          Cope
        </a>
      </footer>
    </div>
  )
}
